INSERT INTO Genres(Name, Description) VALUES('Romantic Comedy', 'A light, comic movie or other work whose plot focuses on the development of a romantic relationship.');
INSERT INTO Genres(Name, Description) VALUES('Drama', 'In film and television, drama is a category or genre of narrative fiction (or semi-fiction) intended to be more serious than humorous in tone.');
INSERT INTO Genres(Name, Description) VALUES('Horror', 'The Dictionary of Film Studies defines the horror film as representing: disturbing and dark subject matter, seeking to elicit responses of fear, terror, disgust, shock, suspense, and, of course, horror from their viewers.');
INSERT INTO Genres(Name, Description) VALUES('Action', 'Action film is a film genre in which the protagonist is thrust into a series of events that typically involve violence and physical feats.');
INSERT INTO Genres(Name, Description) VALUES('Sci-fi', 'Sci-fi is form of fiction that deals principally with the impact of actual or imagined science upon society or individuals.');

INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Brian Helgeland', 'Brian Thomas Helgeland is an American screenwriter, film producer and director. He is most known for writing the screenplays for the films L.A. Confidential and Mystic River.', '01-17-1961');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Roberto Benigni', 'Roberto Remigio Benigni Cavaliere di Gran Croce is an Italian actor, comedian, screenwriter and director. He gained international recognition for writing, directing and starring in the Holocaust comedy-drama film Life Is Beautiful (1997), for which he received the Academy Awards for Best Actor and Best International Feature Film. Benigni remains the only actor to win the Best Actor Academy Award for a non-English language performance.', '10-27-1952');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Scott Cooper', 'Scott Cooper is an American director, screenwriter, producer and actor. He is known for writing and directing Crazy Heart (2009), Out of the Furnace (2013), Black Mass (2015), and Hostiles (2017). Abingdon, Virginia, U.S.', '04-20-1970');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Robert Zemeckis', 'Robert Lee Zemeckis is an American filmmaker. He first came to public attention as the director of the action-adventure romantic comedy Romancing the Stone, the science-fiction comedy Back to the Future film trilogy, and the live-action/animated comedy Who Framed Roger Rabbit.', '05-14-1952');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Wes Craven', 'Wesley Earl Craven was an American film director, screenwriter, producer, actor, and editor. Craven has commonly been recognized as one of the greatest masters of the horror genre due to the cultural impact and influence of his work.', '08-02-1939');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Steven Spielberg', 'Steven Allan Spielberg KBE is an American filmmaker. A major figure of the New Hollywood era and pioneer of the modern blockbuster, he is the most commercially successful director of all time.', '12-18-1946');
INSERT INTO Directors(Name, Bio, Birthyear) VALUES('Gil Junger', 'Gil Junger is an American director, most famous for 10 Things I Hate About You, his directorial film debut. He is a 1972 graduate of the Trinity-Pawling School in Pawling, New York.', '11-17-1954');

INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('A Knights Tale', 'After his master dies, a peasant squire, fueled by his desire for food and glory, creates a new identity for himself as a knight.', 1, 1, 'KT.jpeg', True);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('Life is Beautiful', 'A gentle Jewish-Italian waiter, Guido Orefice (Roberto Benigni), meets Dora (Nicoletta Braschi), a pretty schoolteacher, and wins her over with his charm and humor. Eventually they marry and have a son, Giosue. Their happiness is abruptly halted, however, when Guido and Giosue are separated from Dora and taken to a concentration camp. Determined to shelter his son from the horrors of his surroundings, Guido convinces Giosue that their time in the camp is merely a game.', 2, 2, 'Vitaebella.jpeg', False);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('The Pale Blue Eye', 'A world-weary detective is hired to investigate the murder of a West Point cadet. Stymied by the cadets code of silence, he enlists one of their own to help unravel the case - a young man the world would come to know as Edgar Allan Poe.', 3, 3, 'PBE.jpeg', False);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('Flight', 'An airline pilot saves almost all his passengers on his malfunctioning airliner which eventually crashed, but an investigation into the accident reveals something troubling.', 4,4, 'Flight.jpeg', True);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',2,4, 'FGP.jpeg', True); 
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('A Nightmare on Elm Street','Teenager Nancy Thompson must uncover the dark truth concealed by her parents after she and her friends become targets of the spirit of a serial killer with a bladed glove in their dreams, in which if they die, it kills them in real life.', 3,5, 'Freddy.jpeg', True);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('Ready Player One', 'When the creator of a virtual reality called the OASIS dies, he makes a posthumous challenge to all OASIS users to find his Easter Egg, which will give the finder his fortune and control of his world.', 5,6, 'rp1.jpeg', True);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('Legend','Legend is adapted from John Pearson''s book The Profession of Violence: The Rise and Fall of the Kray Twins, which deals with their career and the relationship that bound them together, and follows their gruesome career to life imprisonment in 1969.', 2,1,'legend.jpeg', True);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('10 Things I Hate About You', 'The film follows new student Cameron who is smitten with Bianca and, in order to get around her father''s strict rules on dating, attempts to get bad boy Patrick to date Bianca''s antisocial sister, Kat. The film is named after a poem Kat writes about her romance with Patrick.', 1,7, '10things.jpeg', False);
INSERT INTO Movies(Title, Description, GenreID, DirectorID,ImageUrl,Featured) VALUES('Beauty and the Briefcase','A freelance writer looking for romance sells a story to Cosmopolitan magazine about finding love in the workplace and goes undercover at a Finance Company.', 2,7, 'Bab.jpeg', False);

INSERT INTO Users(Username, password, email, birth_date) VALUES('Lizzie', 'lizzibelle', 'lizziemcguire@gmeil.com', 'April 23, 1994');
INSERT INTO Users(Username, password, email, birth_date) VALUES('Tom', 'tomgun', 'tomastoe@jotmail.com', 'July 15, 1986');
INSERT INTO Users(Username, password, email, birth_date) VALUES('Kai', 'kaimaitai', 'kaimai@gmeil.com', 'May 3, 2000');

INSERT INTO User_movies(userid, movieid) VALUES(1, 1);
INSERT INTO User_movies(userid, movieid) VALUES(2, 2);
INSERT INTO User_movies(userid, movieid) VALUES(3, 6);